
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 19 16:08:42 PDT 2017
//----------------------------------------------------

package translator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEPTEMBER = 33;
  public static final int WEDNESDAY = 20;
  public static final int THE = 44;
  public static final int SHORT = 39;
  public static final int JANUARY = 25;
  public static final int WITH = 12;
  public static final int SLASH = 41;
  public static final int REMOVE = 6;
  public static final int MONDAY = 18;
  public static final int OCTOBER = 34;
  public static final int TUESDAY = 19;
  public static final int THURSDAY = 21;
  public static final int OUR = 51;
  public static final int DATE = 10;
  public static final int ITS = 47;
  public static final int DELETE = 5;
  public static final int HER = 49;
  public static final int OBJECT = 40;
  public static final int IN = 16;
  public static final int JUNE = 30;
  public static final int SATURDAY = 23;
  public static final int NOVEMBER = 35;
  public static final int ON = 15;
  public static final int TODAY = 17;
  public static final int MARCH = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ADD = 4;
  public static final int SUNDAY = 24;
  public static final int AUGUST = 32;
  public static final int CHANGE = 9;
  public static final int FRIDAY = 22;
  public static final int FROM = 14;
  public static final int INTLITERAL = 43;
  public static final int MOVE = 8;
  public static final int errorlex = 53;
  public static final int CANCEL = 7;
  public static final int COMMITMENT = 11;
  public static final int TO = 52;
  public static final int DECEMBER = 36;
  public static final int MEDIUM = 38;
  public static final int CREATE = 2;
  public static final int YOUR = 46;
  public static final int JULY = 31;
  public static final int HOUR = 42;
  public static final int LONG = 37;
  public static final int STRINGLITERAL = 54;
  public static final int MAKE = 3;
  public static final int THEIR = 50;
  public static final int AT = 13;
  public static final int MY = 45;
  public static final int MAY = 29;
  public static final int APRIL = 28;
  public static final int FEBRUARY = 26;
  public static final int HIS = 48;
}

