/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import translator.DateUtils;

/**
 * window that will be used by the window agent
 *
 * @author Humanoide
 */
public class Intro extends javax.swing.JFrame {

    /**
     * Creates new form Intro
     */
    public Intro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        execute = new javax.swing.JButton();
        field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        execute.setText("execute");

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(field, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(execute)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(execute)
                    .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * this is for customize the JList each day have a different color
     *
     * @param args the command line arguments
     */
    private static DefaultListModel<String> createListModel(ArrayList<Appointment> myListModel) {
        DefaultListModel<String> l = new DefaultListModel<>();

        for (Appointment s : myListModel) {
            l.add(0, s.toString());
        }

        // This causes the. Ethos to exit...
        return l;

    }

    /**
     * update the jList
     *
     * @param scheduleList is the list of appointments
     */
    public void updateList(ArrayList<Appointment> scheduleList) {
        jList1.setModel(createListModel(scheduleList));
        jList1.setCellRenderer(new MyListCellThing(scheduleList));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton execute;
    public javax.swing.JTextField field;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
/**
 * class that represent the cell render, is used for bring format to jList
 * @author Humanoide
 */
class MyListCellThing extends JLabel implements ListCellRenderer {

    ArrayList<Appointment> scheduleList;

    public MyListCellThing(ArrayList<Appointment> scheduleList) {
        setOpaque(true);
        this.scheduleList = scheduleList;
    }

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        setText(value.toString());
        setFont(new Font("Dialog", Font.PLAIN, 18));

        // based on the index you set the color.  This produces the every other effect.
        setBackground(colorOfDay(DateUtils.dayOfWeek(scheduleList.get(scheduleList.size() - index - 1).BeginDate)));

        return this;
    }

    /**
     * return the color by the day of week of the appointment
     *
     * @param day , day of the week
     * @return the color that will displayed in the list
     */
    public static Color colorOfDay(int day) {
        Color[] cArray = new Color[8];
        cArray[0] = new Color(255, 255, 204);
        cArray[1] = new Color(242, 255, 204);
        cArray[2] = new Color(217, 255, 204);
        cArray[3] = new Color(204, 255, 255);
        cArray[4] = new Color(204, 204, 255);
        cArray[5] = new Color(255, 204, 242);
        cArray[6] = new Color(255, 204, 204);
        cArray[7] = new Color(204, 255, 102);
        return cArray[day];
    }
}
